//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeLake
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoffeLakeContainer : DbContext
    {
        public CoffeLakeContainer()
            : base("name=CoffeLakeContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ProductCategory> ProductCategorySet { get; set; }
        public DbSet<Product> ProductSet { get; set; }
        public DbSet<MenuCategory> MenuCategorySet { get; set; }
        public DbSet<CoffeLakeMenu> CoffeLakeMenuSet { get; set; }
        public DbSet<Reviews> ReviewsSet { get; set; }
    }
}
