//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeLake
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuCategory
    {
        public MenuCategory()
        {
            this.CoffeLakeMenu = new HashSet<CoffeLakeMenu>();
        }
    
        public int Id { get; set; }
        public string Caption { get; set; }
    
        public virtual ICollection<CoffeLakeMenu> CoffeLakeMenu { get; set; }
    }
}
